<?php

/**
 * BaseUser_view_video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $video_id
 * @property sfGuardUser $User
 * @property Video $Video
 * 
 * @method integer         getUserId()   Returns the current record's "user_id" value
 * @method integer         getVideoId()  Returns the current record's "video_id" value
 * @method sfGuardUser     getUser()     Returns the current record's "User" value
 * @method Video           getVideo()    Returns the current record's "Video" value
 * @method User_view_video setUserId()   Sets the current record's "user_id" value
 * @method User_view_video setVideoId()  Sets the current record's "video_id" value
 * @method User_view_video setUser()     Sets the current record's "User" value
 * @method User_view_video setVideo()    Sets the current record's "Video" value
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser_view_video extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_view_video');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}