<?php

/**
 * BaseTwitterProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $access_token
 * @property string $access_token_secret
 * @property integer $user_id
 * @property sfGuardUser $Users
 * 
 * @method integer        getId()                  Returns the current record's "id" value
 * @method string         getUsername()            Returns the current record's "username" value
 * @method string         getAccessToken()         Returns the current record's "access_token" value
 * @method string         getAccessTokenSecret()   Returns the current record's "access_token_secret" value
 * @method integer        getUserId()              Returns the current record's "user_id" value
 * @method sfGuardUser    getUsers()               Returns the current record's "Users" value
 * @method TwitterProfile setId()                  Sets the current record's "id" value
 * @method TwitterProfile setUsername()            Sets the current record's "username" value
 * @method TwitterProfile setAccessToken()         Sets the current record's "access_token" value
 * @method TwitterProfile setAccessTokenSecret()   Sets the current record's "access_token_secret" value
 * @method TwitterProfile setUserId()              Sets the current record's "user_id" value
 * @method TwitterProfile setUsers()               Sets the current record's "Users" value
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTwitterProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('twitter_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('username', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('access_token', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('access_token_secret', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Users', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}