<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $fb_id
 * @property string $username
 * @property string $message
 * @property integer $video_id
 * @property Video $Video
 * 
 * @method string  getFbId()     Returns the current record's "fb_id" value
 * @method string  getUsername() Returns the current record's "username" value
 * @method string  getMessage()  Returns the current record's "message" value
 * @method integer getVideoId()  Returns the current record's "video_id" value
 * @method Video   getVideo()    Returns the current record's "Video" value
 * @method Comment setFbId()     Sets the current record's "fb_id" value
 * @method Comment setUsername() Sets the current record's "username" value
 * @method Comment setMessage()  Sets the current record's "message" value
 * @method Comment setVideoId()  Sets the current record's "video_id" value
 * @method Comment setVideo()    Sets the current record's "Video" value
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('fb_id', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('username', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('message', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}