<?php

/**
 * BaseImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $priority
 * @property integer $video_id
 * 
 * @method string  getName()     Returns the current record's "name" value
 * @method string  getPriority() Returns the current record's "priority" value
 * @method integer getVideoId()  Returns the current record's "video_id" value
 * @method Images  setName()     Sets the current record's "name" value
 * @method Images  setPriority() Sets the current record's "priority" value
 * @method Images  setVideoId()  Sets the current record's "video_id" value
 * @property video $
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('images');
        $this->hasColumn('name', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('priority', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('video', array(
             'local' => 'video_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}