<?php

/**
 * BaseCommentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $message
 * @property integer $user_id
 * @property integer $video_id
 * @property sfGuardUser $Users
 * @property Video $Video
 * 
 * @method string      getMessage()  Returns the current record's "message" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method integer     getVideoId()  Returns the current record's "video_id" value
 * @method sfGuardUser getUsers()    Returns the current record's "Users" value
 * @method Video       getVideo()    Returns the current record's "Video" value
 * @method Commentaire setMessage()  Sets the current record's "message" value
 * @method Commentaire setUserId()   Sets the current record's "user_id" value
 * @method Commentaire setVideoId()  Sets the current record's "video_id" value
 * @method Commentaire setUsers()    Sets the current record's "Users" value
 * @method Commentaire setVideo()    Sets the current record's "Video" value
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commentaire');
        $this->hasColumn('message', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Users', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}