<?php

/**
 * BaseSearch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $content
 * 
 * @method string getContent() Returns the current record's "content" value
 * @method Search setContent() Sets the current record's "content" value
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSearch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('search');
        $this->hasColumn('content', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}