<?php

/**
 * BaseFacebookProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $access_token
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method string          getAccessToken()  Returns the current record's "access_token" value
 * @method integer         getUserId()       Returns the current record's "user_id" value
 * @method sfGuardUser     getUser()         Returns the current record's "User" value
 * @method FacebookProfile setId()           Sets the current record's "id" value
 * @method FacebookProfile setAccessToken()  Sets the current record's "access_token" value
 * @method FacebookProfile setUserId()       Sets the current record's "user_id" value
 * @method FacebookProfile setUser()         Sets the current record's "User" value
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacebookProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facebook_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('access_token', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}