# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  flux:
    flux_list:
      - http://feeds.feedburner.com/blogmarrant
      - http://www.fail-buzz.com/feed/
