<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/03/30 01:43:34
$this->security = array (
  'new' => 
  array (
    'is_secure' => true,
  ),
  'edit' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
