<?php

/**
 * Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
	public function getExcerpt($lg_max)
	{
		$chaine = $this->getMessage();
		if (strlen($chaine) > $lg_max)
		{
			$chaine = substr($chaine, 0, $lg_max);
			$last_space = strrpos($chaine, " ");
			$chaine = substr($chaine, 0, $last_space)."...";
		}
		return $chaine;
	}
}
