<?php

/**
 * Config
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Config extends BaseConfig
{
	public static function getConfig($name)
	{
		$q = Doctrine_Core::getTable('Config')
      		->createQuery('c')
			->select('c.content')
      		->where('c.name = ?', $name);

		return $q->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
	}
}
