<?php

/**
 * FacebookProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacebookProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacebookProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacebookProfile');
    }
}