<?php

/**
 * FriteuseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FriteuseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FriteuseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Friteuse');
    }
}