<?php

/**
 * ImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Images');
    }
}