<?php

/**
 * SearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SearchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Search');
    }
}