<?php

/**
 * TwitterProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TwitterProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TwitterProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TwitterProfile');
    }
}