<?php

/**
 * User_like_videoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_like_videoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_like_videoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_like_video');
    }
}