<?php

/**
 * User_like_video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jolatefri
 * @subpackage model
 * @author     Antoine Lenoir
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_like_video extends BaseUser_like_video
{public function getTimeLapse()
	{
		$datetime1 = date_create($this->getCreatedAt());
		$datetime2 = date_create('now');
		$interval = date_diff($datetime1, $datetime2);
		if($interval->format('%y'))
		{
			return ' il y a '.$interval->format('%y').' ans';
		}
		elseif($interval->format('%m'))
		{
			return ' il y a '.$interval->format('%m').' mois';
		}
		elseif($interval->format('%d'))
		{
			return ' il y a '.$interval->format('%d').' jours';
		}
		elseif($interval->format('%h'))
		{
			return ' il y a '.$interval->format('%h').' heures';
		}
		elseif($interval->format('%i'))
		{
			return ' il y a '.$interval->format('%i').' minutes';
		}
	}
	
		
	public function getModelName()
  	{
    	return 'User_like_video';
  	}
}
