<?php

/**
 * User_like_friteuseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_like_friteuseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_like_friteuseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_like_friteuse');
    }
}