<?php

/**
 * VideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Video');
    }
    
    public static function updateVue($idVideo)
    {
        $q = Doctrine_Query::create()
    		->update('Video')
    		->set('nbVue', 'nbVue + 1')
    		->where('id = ?', array($idVideo))
    		->execute();
        
    }
	
	static public function getLuceneIndex()
	{
	  ProjectConfiguration::registerZend();
	 
	  if (file_exists($index = self::getLuceneIndexFile()))
	  {
	    return Zend_Search_Lucene::open($index);
	  }
	  else
	  {
	    return Zend_Search_Lucene::create($index);
	  }
	}
	 
	static public function getLuceneIndexFile()
	{
	  return sfConfig::get('sf_data_dir').'/video.'.sfConfig::get('sf_environment').'.index';
	}
	
	public function getForLuceneQuery($query)
	{
	 
	  $hits = self::getLuceneIndex()->find($query);

	  $pks = array();
	  foreach ($hits as $hit)
	  {
	    $pks[] = $hit->pk;
	  }
	 
	  if (empty($pks))
	  {
	    return array();
	  }
	 
	  $q = $this->createQuery('v')
	    ->whereIn('v.id', $pks)
	    ->limit(30)
		->orderBy('v.created_at DESC');
	 
	 
	  return $q->execute();
	}
    
}