<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
	
	public function isUnique($username, $id)
	{
		$user = $this->getInstance()->createQuery('sfu')
			->where('username = ?', $username)
			->addWhere('id != ?', $id)
			->execute();
		
		if($user->count())
			return true;
		else {
			return false;
		}
	}
}