<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/13 13:11:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dev',
  'username' => 'jolatefri',
  'password' => 'fvavoe2t',
  'name' => 'doctrine',
)),);
