<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/13 13:12:21
sfConfig::add(array(
  'app_facebook_app_id' => 138964119509027,
  'app_facebook_secret' => '6ff92d7d57213dfcac7d41cf190a8dba',
  'app_facebook_api_key' => '0592435d93acf05076096809c1337b0d',
  'app_facebook_app_secret' => '6ff92d7d57213dfcac7d41cf190a8dba',
  'app_twitter_consumer_key' => 'pwAAqzPkbS0yrZGzygNaFg',
  'app_twitter_consumer_secret' => 'DjiTV5CUFPkRNoBgj8D98Wz3UmItD5PZuTcSkwuACE',
  'app_score_view_video' => 5,
  'app_score_like_video' => 30,
  'app_score_comment_video' => 50,
  'app_score_post_friteuse' => 100,
  'app_max_video_page' => 15,
  'app_video_pub' => array (
  0 => 2600,
  1 => 1863,
  2 => 2602,
  3 => 2117,
  4 => 2275,
  5 => 2154,
  6 => 3076,
  7 => 3704,
  8 => 3264,
),
  'app_coup_coeur' => 3704,
  'app_sf_guard_plugin_remember_key_expiration_age' => 2592000,
  'app_sf_guard_plugin_remember_cookie_name' => 'jolatefriRememberMe',
  'app_sfSimpleGoogleSitemap_orm' => 'Doctrine',
  'app_sfSimpleGoogleSitemap_urls' => array (
  'homepage' => 
  array (
    'url' => 'http://www.jolatefri.com',
    'freq' => 'daily',
    'priority' => 1,
  ),
),
  'app_sfSimpleGoogleSitemap_models' => array (
  'video' => 
  array (
    'model' => 'Video',
    'module' => 'video',
    'action' => 'index',
    'routing' => '@video_show',
    'params' => 
    array (
      'title' => 'getSlugTitle',
      'id' => 'getId',
      'category' => 'getCategory',
    ),
    'date' => 'getLastMod',
    'criteria' => 
    array (
      0 => 
      array (
        'column' => 'is_activated',
        'method' => 'IsActivated',
        'operator' => '=',
        'value' => 1,
      ),
      1 => 
      array (
        'column' => 'slug',
        'method' => 'slug',
        'operator' => '=',
        'value' => '',
      ),
    ),
    'order_by' => 
    array (
      'column' => 'id',
      'method' => 'Id',
      'sort' => 'desc',
    ),
    'limit' => 1000,
    'freq' => 'weekly',
    'priority' => 0.8,
  ),
  'video_new' => 
  array (
    'model' => 'Video',
    'module' => 'video',
    'action' => 'index',
    'routing' => '@video_show_new',
    'params' => 
    array (
      'slug' => 'getSlug',
      'category' => 'getCategory',
    ),
    'date' => 'getLastMod',
    'criteria' => 
    array (
      0 => 
      array (
        'column' => 'is_activated',
        'method' => 'IsActivated',
        'operator' => '=',
        'value' => 1,
      ),
      1 => 
      array (
        'column' => 'slug',
        'method' => 'slug',
        'operator' => '!=',
        'value' => '',
      ),
    ),
    'order_by' => 
    array (
      'column' => 'id',
      'method' => 'Id',
      'sort' => 'desc',
    ),
    'limit' => 1000,
    'freq' => 'weekly',
    'priority' => 0.8,
  ),
  'category' => 
  array (
    'model' => 'Friteuse',
    'module' => 'friteuse',
    'action' => 'index',
    'routing' => '@friteuse_show_new',
    'params' => 
    array (
      'slug' => 'getSlug',
    ),
    'date' => 'getLastMod',
    'criteria' => 
    array (
      0 => 
      array (
        'column' => 'slug',
        'method' => 'IsActivated',
        'operator' => '!=',
        'value' => '',
      ),
    ),
    'limit' => 1000,
    'freq' => 'daily',
    'priority' => 0.5,
  ),
),
));
